# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='okr_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
