# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingresult',
            name='average_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='first_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='fourth_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='games_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='second_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='tenhou_rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='third_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'RR'], [2, 'CRR'], [1, 'EMA'], [3, 'OKR']]),
        ),
    ]
